version: "3.8"

services:
  todo-app:
    image: ahmedmaged6/fortstak:latest
    container_name: todo-container
    ports:
      - "8000:4000"
    env_file:
      - .env
    environment:
      - mongoDbUrl=${mongoDbUrl}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q" ,"http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - DOCKER_CONFIG=/  # Tells Watchtower to look at /config.json
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
    command: todo-container

